name: Black formatter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: black formatter
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.x
      
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install "black<24"

    - name: Format with black
      run: |
        black --diff --check $(git ls-files '*.py')
